### ISSUE TITLE
Lots of issues compiling this

### ISSUE THREAD

**Issue by xavierjefferson** [FubarDevelopment/FtpServer#1]
I'm using VS2013.

1>------ Build started: Project: FubarDev.FtpServer.FileSystem, Configuration: Debug Any CPU ------
2>------ Build started: Project: FubarDev.FtpServer.AccountManagement, Configuration: Debug Any CPU ------
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\FileSystemExtensions.cs(197,31,197,32): error CS1056: Unexpected character '$'
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\FileSystemExtensions.cs(211,28,211,29): error CS1056: Unexpected character '$'
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\ListSegment.cs(29,34,29,36): error CS1514: { expected
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\ListSegment.cs(29,41,29,42): error CS1519: Invalid token '[' in class, struct, or interface member declaration
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\ListSegment.cs(29,50,29,51): error CS1003: Syntax error, ']' expected
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\ListSegment.cs(29,50,29,51): error CS1519: Invalid token '+' in class, struct, or interface member declaration
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\ListSegment.cs(29,57,29,58): error CS1519: Invalid token ']' in class, struct, or interface member declaration
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\MemoryTemporaryData.cs(29,26,29,28): error CS1002: ; expected
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\MemoryTemporaryData.cs(29,35,29,36): error CS1519: Invalid token '.' in class, struct, or interface member declaration
1>C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\MemoryTemporaryData.cs(29,43,29,45): error CS1519: Invalid token '??' in class, struct, or interface member declaration
2>  FubarDev.FtpServer.AccountManagement -> C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.AccountManagement\bin\Debug\FubarDev.FtpServer.AccountManagement.dll
3>------ Build started: Project: FubarDev.FtpServer.FileSystem.DotNet, Configuration: Debug Any CPU ------
4>------ Build started: Project: FubarDev.FtpServer, Configuration: Debug Any CPU ------
3>CSC : error CS0006: Metadata file 'C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\bin\Debug\FubarDev.FtpServer.FileSystem.dll' could not be found
4>CSC : error CS0006: Metadata file 'C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\bin\Debug\FubarDev.FtpServer.FileSystem.dll' could not be found
5>------ Build started: Project: TestFtpServer, Configuration: Debug Any CPU ------
5>CSC : error CS0006: Metadata file 'C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer\bin\Debug\FubarDev.FtpServer.dll' could not be found
5>CSC : error CS0006: Metadata file 'C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem\bin\Debug\FubarDev.FtpServer.FileSystem.dll' could not be found
5>CSC : error CS0006: Metadata file 'C:\Downloads\FtpServer-master\FtpServer-master\FubarDev.FtpServer.FileSystem.DotNet\bin\Debug\FubarDev.FtpServer.FileSystem.DotNet.dll' could not be found
========== Build: 1 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

**Comment by fubar-coder** [comment]
That's the problem. This project uses C# 6 and AFAIK you'll need VS 2015 to compile this.

**Comment by fubar-coder** [comment]
The C# 6 features are definitely worth the upgrade to VS 2015 - and the VS 2015 Community Edition is clearly good enough in most cases.
