### ISSUE TITLE
readTask sometimes stuck on USER command.

### ISSUE THREAD

**Issue by hytgbn** [FubarDevelopment/FtpServer#10]
Hi, 
I'm trying to test FtpServer behavior on osx using Xamarin with Mono 4.2.4 as well as 3.10.0.
This happens mostly when I try to make multiple concurrent connection to ftp server, but also happens when I try to reconnect.

After some debugging, I found that readTask doesn't complete after ftp client sends USER command. I checked tcpdump and confirmed that server ACK'd USER command part.
Interestingly, when I change readTask to synchronous Read() instead of ReadAsync() it could read correct full USER command. Also, if I change the size of buffer in ProcessMessages() to 16, which is "USER anonymous\r\n", it always success to read.

I don't have many experiences on C# especially on OSX. Have you experienced this case before?

Thanks,
hytgbn

**Comment by fubar-coder** [comment]
I'm not aware of any problems during the authentication, but it might be aproblem with mono. A reliable test case is required before I can fix this problem. Thanks for reporting.
