### ISSUE TITLE
Pass an 'FtpServerListenerService' in via the constructor

### ISSUE THREAD

**Issue by robeving** [FubarDevelopment/FtpServer#114]
The creation of the FtpServerListenerService object in the FtpServer constructor is great for people who don't mind this library managing Tcp connections but not for people like me who already have a framework in place to manage and monitor these. Consider allowing a 'IPausableFtpService' interface or similar to be passed in via a constructor overload. That way I can manage the TcpClient object differently.

https://github.com/FubarDevelopment/FtpServer/blob/f2b0e1c62227f2363146dacdc2cf8d0e0c3fb045/src/FubarDev.FtpServer/FtpServer.cs#L56

**Comment by fubar-coder** [comment]
PR #115 is now closed, but the interface is still implemented. Thank you for your support.
