### ISSUE TITLE
How to subscribe the FtpConnectionDataTransferStartedEvent & FtpConnectionDataTransferStoppedEvent event?

### ISSUE THREAD

**Issue by weiluenju** [FubarDevelopment/FtpServer#120]
I am a beginner.

How to subscribe the FtpConnectionDataTransferStartedEvent & FtpConnectionDataTransferStoppedEvent event or how to use?

There is my code:

```
ServiceCollection services = new ServiceCollection();
services.AddFtpServer(builder => {
	builder.UseDotNetFileSystem();
});

services.AddSingleton<IMembershipProvider, MyMembershipProvider>();
services.AddSingleton<IAccountDirectoryQuery, MyAccountDirectoryQuery>();

services.Configure<DotNetFileSystemOptions>(opt =>
	opt.RootPath = ftpRoot
);

services.Configure<FtpServerOptions>(opt => {
	opt.Port = port;
});

services.Configure<SimplePasvOptions>(opt => {
	opt.PasvMinPort = 7000;
	opt.PasvMaxPort = 7100;
});

ServiceProvider serviceProvider = services.BuildServiceProvider();
ftpServerHost = serviceProvider.GetRequiredService<IFtpServerHost>();
ftpServerHost.StartAsync(CancellationToken.None).Wait();
```

Thank you.

**Comment by fubar-coder** [comment]
The `IFtpConnection` implementation also implements `IObservable<IFtpConnectionEvent>`, but you have to register your observer for all connections.

First, you have to create an implementation of `IFtpConnectionConfigurator`. An example for this interface is the class [`AuthTlsConfigurator`](https://github.com/FubarDevelopment/FtpServer/blob/ab1f16ad4c1d9946bd48b005590417ce7ce68aa0/src/FubarDev.FtpServer/CoreFtpServerBuilderExtensions.cs#L70), which is used to implement implicit TLS. Your implementation has to be registered as (singleton!) service too.

Now, you can subscribe the connection events.

```csharp
if (connection is IObservable<IFtpConnectionEvent> observable)
{
  _subscription = observable.Subscribe(new YourEventObserver());
}
```

The class `YourEventObserver` must implement `IObserver<IFtpConnectionEvent>`. In the `OnNext` function, you get a `IFtpConnectionEvent` parameter. `FtpConnectionDataTransferStartedEvent` implements this interface and can be tested fir with pattern matching.

An example for an event observer can be found in the class [`FtpConnectionIdleCheck`](https://github.com/FubarDevelopment/FtpServer/commit/b3e4cdd68ce2a8788c358ffb8882aceef902e319#diff-4af97f94065479a3316c39cc1ae17706b8f895252333a7154e0e779280d4e792).

**Comment by weiluenju** [comment]
I follow your teaching and successfully subscribe the events.

Thank you very much.
