### ISSUE TITLE
Can I host SFTP with this library? 

### ISSUE THREAD

**Issue by AndersMalmgren** [FubarDevelopment/FtpServer#129]
I cant seem to find anything on the subject. 
I tried to host a server and connect to it using a SFTP client but its refused.

**Comment by fubar-coder** [comment]
No, only FTPS. FTPS is FTP over SSL/TLS while SFTP is something FTP-alike over SSH, which is a completely different thing.

**Comment by AndersMalmgren** [comment]
Thanks found something called rebex which cost money and has a aging none async API. But it works. Not has nice API as your solution though
