### ISSUE TITLE
multiple directory for a user

### ISSUE THREAD

**Issue by stephane3434** [FubarDevelopment/FtpServer#130]
how to assign multiple ftp for a user directory. 

as for example 
/myDir1 
/myDir2 
/myDir2/Test 

and then how to assign read/write rights for each folder

should we use InMemoryDirectory and create virtual directories?

I can't see how to do it. 

Thank you

**Comment by fubar-coder** [comment]
1. Every user has only a (virtual) root directory
2. Access rights are managed by the native (OS) file system
3. The in-memory file system should be a good starting point to create what you need
