### ISSUE TITLE
Configure multiple command ports

### ISSUE THREAD

**Issue by BrianAtAFG** [FubarDevelopment/FtpServer#151]
The configuration seems to only support a single command port.  Is it be possible to listen on multiple command ports concurrently?

**Comment by fubar-coder** [comment]
No, it's not supported. Maybe you can run multiple instances?

**Comment by BrianAtAFG** [comment]
> No, it's not supported. Maybe you can run multiple instances?

That may be my workaround.  Do you foresee any issues with instantiating two servers in the same process?  Or will I need to have 2 different processes?  

Would you be interested in a pull request that made a change to allow multiple ports?  Or am I unique with this requirement?

**Comment by fubar-coder** [comment]
You should be able to instantiate two servers by using two different IServiceCollection's.
