### ISSUE TITLE
A simple help wouldn't be bad at all friends 💥

### ISSUE THREAD

**Issue by SnowdenDev** [FubarDevelopment/FtpServer#156]
Please, I can't find how to set a username and password for the ftp server, can someone tell me how I can do it, this is my current code:
static async Task Main(string[] args)
{
    var services = new ServiceCollection();
    services.Configure<DotNetFileSystemOptions>(opt => opt.RootPath = "TestFtpServer");
    services.Configure<FtpServerOptions>(opt => opt.ServerAddress = "127.0.0.1");
    services.AddFtpServer(builder => builder.UseDotNetFileSystem());
    using (var serviceProvider = services.BuildServiceProvider())
    {
        var ftpServerHost = serviceProvider.GetRequiredService<IFtpServerHost>();
        await ftpServerHost.StartAsync();
        Console.WriteLine("Press ENTER/RETURN to close the test application.");
        Console.ReadLine();
        await ftpServerHost.StopAsync();
    }
}

**Comment by fubar-coder** [comment]
You need to provide your own [`IMembershipProvider`](https://fubardevelopment.github.io/FtpServer/api/FubarDev.FtpServer.AccountManagement.IMembershipProvider.html) service.

There is also a small article about the authentication methods supported out of the box: [Authentication](https://fubardevelopment.github.io/FtpServer/articles/authentication.html)

You can also find a sample implementation in this comment: https://github.com/FubarDevelopment/FtpServer/issues/19#issuecomment-333029170
