### ISSUE TITLE
PASS command for successful login should return 230 rather than 220

### ISSUE THREAD

**Issue by alexchilcott** [FubarDevelopment/FtpServer#2]
The RFC doesn't specify 220 as a valid response from the PASS command (see https://www.ietf.org/rfc/rfc959.txt, page 50).

Some clients (such as FileZilla Client) seem to accept the response of 230, but others don't. In particular, the .Net FtpWebRequest class will fail to login to the server.

For what it's worth, FileZilla Server also returns 230.

**Comment by fubar-coder** [comment]
Yes, you're right. I'll fix this.

**Comment by alexchilcott** [comment]
Thanks. Great work with the server.

**Comment by fubar-coder** [comment]
Fixed
