### ISSUE TITLE
.NET Standard Compatibility 

### ISSUE THREAD

**Issue by yulia-d** [FubarDevelopment/FtpServer#27]
Any plans to make this .NET Standard Compatible?

**Comment by fubar-coder** [comment]
A .NET Standard compatible version is in the release/2.0.0 branch. I'm hesitant to release it without testing it properly. Would you be willing to test it if I'd release it as beta version on nuget.org?

**Comment by yulia-d** [comment]
Unfortunately, no time for that at the moment... But thanks for the reply!

**Comment by yulia-d** [comment]
On the other hand, in case I'll get to it eventually, maybe you can do that, i.e. release the beta?
Besides, perhaps there'll be others who'll jump on it? This library appears the only reputable one on NuGet that provides server functionality...

**Comment by fubar-coder** [comment]
2.0 is released and [documentation is available](http://fubardevelopment.github.io/FtpServer/). There is also a [quickstart tutorial](http://fubardevelopment.github.io/FtpServer/articles/quickstart.html).
