### ISSUE TITLE
Request for complete Documentation

### ISSUE THREAD

**Issue by dhutapratama** [FubarDevelopment/FtpServer#28]
I like this library from first launch and using it for my simple project.
But after updating to 2.0.0-beta.36, I get lost in everything.

Please update to the newest documentation.
Just simple explanation with rich syntax for every feature.

Thank you very much

**Comment by fubar-coder** [comment]
I'm currently writing the new documentation. What are your major pain points?

**Comment by fubar-coder** [comment]
I've published version 2.0 and added some [documentation](http://fubardevelopment.github.io/FtpServer/). There is also a [quickstart tutorial](http://fubardevelopment.github.io/FtpServer/articles/quickstart.html).
