### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions

### ISSUE THREAD

**Issue by remeezp** [FubarDevelopment/FtpServer#29]
Hi,

I am getting the follow error when running a .net core 2.0 console app, with the suggested code in Program.cs.

> System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions`1[FubarDev.FtpServer.FtpServerOptions]' while attempting to activate 'FubarDev.FtpServer.FtpServer'.'

**Comment by fubar-coder** [comment]
Fixed in version 2.0.1 which will be released soon.
