### ISSUE TITLE
Can't get a listing

### ISSUE THREAD

**Issue by talanc** [FubarDevelopment/FtpServer#3]
I can't get a listing using System.Net.FtpClient and FtpServer. I create the server and try a listing and this this the result: https://github.com/talanc/FtpServerTest/blob/master/FtpServerTest/TestCreated.ClientError.txt

I ran the Sample Ftp Server provided and here's the server log: https://github.com/talanc/FtpServerTest/blob/master/FtpServerTest/TestLocal.ServerDebug.txt

I thought I might be using System.Net.FtpClient incorrectly, but I've included a Test Case for ftp.gnu.org and it works.

Is it something on my computer I need to do?

**Comment by fubar-coder** [comment]
That is strange. ```PASV``` works, but not ```EPSV```. It seems that the connection gets reset after the ```EPSV``` got received, but my code doesn't close the connection. I'll have to do further investigation.

**Comment by ChronosWS** [comment]
Also hitting this under the same conditions.

**Comment by talanc** [comment]
It works now -- thank you.
