### ISSUE TITLE
FtpServer custom ftp user v2.1.1

### ISSUE THREAD

**Issue by kyndeyrn** [FubarDevelopment/FtpServer#30]
Hello,

I'm unable to get the custom FTP user to work.

Scenario:
connect with a simple username+password to the ftp server.

It worked before with version 1.3.7, but with the newer version, I'm not sure how to implement this.

Would it be possible to write a small & easy example?

Best regards & Thanks,
Kyndeyrn

**Comment by fubar-coder** [comment]
I added a `CustomMembershipProvider.cs` to `samples/TestFtpServer`.

This is what you should do:

1. Copy the `CustomMembershipProvider` from the sample application
2. Remove the call to `EnableAnonymousAuthentication`
3. Add a singleton for your `CustomMembershipProvider` with `services.AddSingleton<IMembershipProvider, CustomMembershipProvider>()`

Done :)

**Comment by rosscpeterson** [comment]
I'm confused slightly by this.
I've done your steps above, but I'm left wondering how I add a user (a CustomerMembershipProvider) to the server?

I would naïvely expect something like this:
```
FtpUserMembershipProvider ftpUserMembershipProvider = new FtpUserMembershipProvider(ftpUID, ftpPID);
services.AddSingleton<IMembershipProvider, FtpUserMembershipProvider>();
services.AddSingleton<IMembershipProviderInstance>(ftpUserMembershipProvider);
```

**Comment by fubar-coder** [comment]
I cannot reproduce this problem, but I can give you some hints:

1. Create a `CustomMembershipProvider` class (see below)
2. Register it with `services.AddSingleton<IMembershipProvider, CustomMembershipProvider>()`
3. Remove the call to `EnableAnonymousAuthentication()`

# CustomMembershipProvider

```cs
private class CustomMembershipProvider : IMembershipProvider
{
    /// <inheritdoc />
    public Task<MemberValidationResult> ValidateUserAsync(string username, string password)
    {
        if (username == "tester" && password == "test")
        {
            var identity = new ClaimsIdentity();
            return Task.FromResult(
                new MemberValidationResult(
                    MemberValidationStatus.AuthenticatedUser,
                    new ClaimsPrincipal(identity)));
        }

        return Task.FromResult(new MemberValidationResult(MemberValidationStatus.InvalidLogin));
    }
}
```

The membership provider takes care of the validation of the user name and password and returns a `ClaimsPrincipal` instance in case of a successful validation. This is the point where you implement your own user/password validation.

**Comment by rosscpeterson** [comment]
Thanks for the quick reply.
One strange issue that seems to indicate a version mismatch:

The 2nd argument of the MemberValidationResult constructor in my code doesn't accept a ClaimsPrincipal, but wants a FubarDev.FtpServer.AccountManagement.IFtpUser.

Why does yours expect a ClaimsPrincipal while mine expects a IFtpUser?

I implemented my own IFtpUser class and I passed that in, but I'm having the same problem as before.

I'm using version 3.0.1 of the FubarDev Nuget packages: 
- FubarDev.FtpServer
- FubarDev.FtpServer.Abstractions
- FubarDev.FtpServer.Commands
- FubarDev.FileSystem.DotNet

**Comment by fubar-coder** [comment]
You're correct. 3.0.1 doesn't contain this constructor yet. I'll switch to ClaimsPrincipal for 3.1, but keep the old code, marked as obsolete.

I'm unable to reproduce the problem. Can you upload a sample (zip file) or give me access to a sample repository?

**Comment by fubar-coder** [comment]
OK, I see at least on problem:

The `FtpUserMembershipProvider` class cannot be instantiated via dependency injection, because it's unable to provide the parameters for its constructors.

Have you tried using my sample code above? It should work out of the box with user name "tester" and password "test". When you replace the username with `Connection.FTUID` and the password with `Connection.FTPID`, then everything should start working immediately.

**Comment by rosscpeterson** [comment]
OK. I can log in now. 
Thank you very much for the help!

**Comment by robokamran** [comment]
Update: IFtpUser is obsolete, use sample code in here:
https://github.com/FubarDevelopment/FtpServer/blob/master/samples/TestFtpServer/CustomMembershipProvider.cs

**Comment by akanshSirohi** [comment]
I want to generate a different password every time the FTP server start, I am not getting the point that how can I pass the different username and password...???

**Comment by robokamran** [comment]
@akanshSirohi, I think a good way would be to store the password in the DB each time the server starts, then validate the input password with the stored passwords in the DB (each time the validation is needed).
