### ISSUE TITLE
Membership Provider only supports synchronous validations

### ISSUE THREAD

**Issue by lafe** [FubarDevelopment/FtpServer#34]
The current implementation of the `IMembershipProvider` only offers a synchronous endpoint. This means that using APIs with asynchronous endpoints to perform the validation is more difficult than it should be, especially since the calling code is already async.

**Comment by fubar-coder** [comment]
I'm hesitant to add this yet, because I'd just change the IMembershipProvider member to async and bump the major version.

**Comment by fubar-coder** [comment]
Version 3.0-beta.1 is released.
