### ISSUE TITLE
LIST command not working when using NuGet package DotNet.Glob newer than 2.0.0

### ISSUE THREAD

**Issue by MartinBuehlmann** [FubarDevelopment/FtpServer#37]
FubarDev.FtpServer has a dependency to DotNet.Glob >= 2.0.0. But when updating to newer package versions than 2.0.0 and trying to retrieve a directory content list (LIST), parsing the command fails. Other commands like downloading a file (GET) work.

**Comment by fubar-coder** [comment]
Do you get an error message? I cannot reproduce the problem here.

**Comment by MartinBuehlmann** [comment]
![repro](https://user-images.githubusercontent.com/1773717/44778809-377d7d00-ab7e-11e8-9bb4-3b5c2f9c8773.png)
Using ftp command line tool (Windows 10) and executing a dir command, I get "501 Syntax error in parameters or arguments."
(With DotNet.Glob 2.1.0)

**Comment by fubar-coder** [comment]
Can you send me an error log from the server?

**Comment by MartinBuehlmann** [comment]
Ok, I see that it does not find DotNet.Glob version 2.0.0.0 since I updated the package to 2.1.0.0.

System.IO.FileLoadException:  Could not load file or assembly 'DotNet.Glob, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'DotNet.Glob, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

And it looks like they changed the publicKeyToken of the assembly, so a assembly redirect does not work.

**Comment by fubar-coder** [comment]
That makes sense. I always tested using .NET Core, which automatically does an assembly redirect and ignores public key tokens.

I don't see this as an issue in the FTP server itself, but I'll leave this issue open as a reminder to use another globbing implementation. Please create an issue for the [DotNet.Glob project](https://github.com/dazinator/DotNet.Glob).

**Comment by MartinBuehlmann** [comment]
I would say they changed it the right way. They had no public key token earlier and now they have one. So next time when you make a release using the newest DotNet.Glob library, all will be fine. It is not an issue with them . Just update the dependency of your NuGet package to >= 2.0.1 and everything will be fine.

**Comment by fubar-coder** [comment]
It's a breaking change. It breaks binary compatibility. This should only happen between major versions, not minor versions, so it's definitely their problem. As Linus says: Don't break user space. This situation is similar. I'm the user of `DotNet.Glob` and they broke this library.
