### ISSUE TITLE
allow use with dot net 4.6 by not requiring dependency injection

### ISSUE THREAD

**Issue by beppe9000** [FubarDevelopment/FtpServer#39]
pls allow to use without DI

**Comment by fubar-coder** [comment]
Sorry, but this is not going to happen. The next major version will be implemented as a [.NET Generic Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host) and will  also use `Span<T>` and [pipelines](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/)

**Comment by Aida-Enna** [comment]
This is the reason why I can't get ``var services = new IServiceCollection();`` to work no matter what I do, isn't it? =/ Any news on this?

**Comment by fubar-coder** [comment]
You cannot instantiate an `IServiceCollection`, as it's just a non-COM interface. You need a `ServiceCollection` class as provided by the `Microsoft.Extensions.DependencyInjection` package or something that's compatible with it (e.g. AutoFac with support for the interfaces as defined in the `Microsoft.Extensions.DependencyInjection.Abstractions` package.
