### ISSUE TITLE
Listener address on remote server

### ISSUE THREAD

**Issue by ArrowCase** [FubarDevelopment/FtpServer#43]
Because the ServerAddress setting is a literal string that gets fed through `Dns.GetHostAddressesAsync`, there is no way to specify `IPAddress.All` in the `TcpListener`, which would be convenient for hosting on a remote server where you don't want to have to add in the VM's hostname or local IP.

**Comment by fubar-coder** [comment]
You can use 0.0.0.0 instead.

**Comment by ArrowCase** [comment]
Interesting -- it looks like there is a difference in behavior between two apps I was using for testing, one a .NET Core console application and the other an  ASP .NET Core web application (which launches the FTP server in the background). The console application starts up fine with a 0.0.0.0 binding, but the web app throws the following:

```
crit: FubarDev.FtpServer.FtpServer[0]
      IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses
            that cannot be used as a target address.
      Parameter name: hostName
System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0
      are unspecified addresses that cannot be used as a target address.
Parameter name: hostName
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_0(String arg, AsyncCallback requestCallback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1](Func`4 beginMethod, Func`2 endMethod, TArg1 arg1, Object state)
   at System.Net.Dns.GetHostAddressesAsync(String hostNameOrAddress)
   at FubarDev.FtpServer.MultiBindingTcpListener.StartAsync()
   at FubarDev.FtpServer.FtpServer.<ExecuteServerListener>b__37_0()
```

In any event, the web application was just being used for testing purposes, so if 0.0.0.0 works in the console app then my issue is resolved.

**Comment by ArrowCase** [comment]
0.0.0.0 does not appear to work. The application starts up successfully, but the FTP server cannot actually be reached, locally or from outside the network.

Note that I'm 100% sure that my connectivity/firewalls/etc. are set up properly. If I bind to 127.0.0.1, I can connect to the server locally, and if I bind to 10.0.0.4 I can connect locally or remotely. If I switch from 10.0.0.4 to 0.0.0.0, local and remote access both stop working.

**Comment by chaseaucoin** [comment]
So i have been having the same issue trying to get this containerized. I borught down a local copy and instead of using Dns.GetHostAddressesAsync in the MultiBindingTcpListener I added the following bits of code. Which got everything connecting up fine but now I'm having an issue with PASV beause I have to have well a well defined port range for a containers.

`if(_address == "0.0.0.0")
            {
                try
                {
                    Port = StartListeningAll(_port);
                    return;
                }
                catch
                {
                    Stop();
                    throw;
                }
            }` 

`
    private int StartListeningAll(int port)
        {
            var selectedPort = port;
            
            var listener = new TcpListener(IPAddress.Any, selectedPort);
            listener.Start();

            if (selectedPort == 0)
            {
                selectedPort = ((IPEndPoint)listener.LocalEndpoint).Port;
            }

            _listeners.Add(listener);

            return selectedPort;
        }
`

**Comment by ArrowCase** [comment]
@fubar-coder What do you think about allowing the user to specify an IPAddress instead of a string in the FtpServerOptions? I'd be happy to submit a PR along those lines.

**Comment by chaseaucoin** [comment]
> @fubar-coder What do you think about allowing the user to specify an IPAddress instead of a string in the FtpServerOptions? I'd be happy to submit a PR along those lines.

The only thing to keep in mind is backwards compatibility.  Gotta be able to do either.

**Comment by fubar-coder** [comment]
I'd gladly take this PR 👍

**Comment by Shinetaku** [comment]
When this issue be published to nuget?

Now remote address is not worked in docker container.

**Comment by pnuzhdin** [comment]
@fubar-coder could you, please, release the fix to NuGet?
