### ISSUE TITLE
Can't connect with FileZilla

### ISSUE THREAD

**Issue by ArrowCase** [FubarDevelopment/FtpServer#44]
Environment: Windows 10

Steps to reproduce:
1. Follow quick start guide
2. Connect to localhost with the FileZilla FTP client

Results:

![image](https://user-images.githubusercontent.com/44978869/48511469-cf594180-e824-11e8-8f95-739ebee578ed.png)

Everything works fine when connecting to localhost with another FTP client, like WinSCP or just Google Chrome.

Even though the quick start server is not configured for TLS, I think FileZilla will always try to connect with FTPS/SFTP/whatever before falling back to unencrypted. When connecting to other FTP servers without encryption, FileZilla always logs a message like "server does not support FTP over TLS" as it connects. With the Fubar FtpServer, we never get far enough to see that message. So the issue might be the server not gracefully handling FileZilla's attempt to initiate a TLS connection.

-------------

Related issue: I have also deployed an FtpServer instance to a remote server and set up FTPS on it with a proper certificate. That seems to be working fine, as I can connect to it with WinSCP and it apparently succeeds with an encrypted connection.

![image](https://user-images.githubusercontent.com/44978869/48511375-830e0180-e824-11e8-89b9-007f09d76b58.png)

In this scenario, FileZilla gets a little further than previously, but it still has issues. It's able to connect, prompting me to trust the certificate, and logs in successfully, but then dies with another TLS-related error when attempting to get the directory listing.

![image](https://user-images.githubusercontent.com/44978869/48511400-9c16b280-e824-11e8-8335-a12d3f8f0064.png)

**Comment by chaseaucoin** [comment]
I have the same issue. For now I'm just using the plain FTP protocol this is not ideal for long term but for now it works. 

![image](https://user-images.githubusercontent.com/11601228/48511987-e0528480-e81d-11e8-8124-dfb5f474e4d7.png)

**Comment by avonheimburg** [comment]
FYI, the first part of your issue should be fixed now that pull request #51 has been merged

**Comment by fubar-coder** [comment]
Related: dotnet/corefx#8811

**Comment by fubar-coder** [comment]
Version 3.0-beta.1 is released which should fix your first issue (AUTH TLS with server without certificate).

**Comment by ArrowCase** [comment]
Thanks, I'll give it a try. For the first issue, is calling the `ShutdownAsync()` API not possible as a workaround?

For the second issue, here's a [gist](https://gist.github.com/ArrowCase/5f37062966ed4b78a4744a35a34494f4) of a connection log from [ftptest.net](https://ftptest.net/) to my server. It seems that the "unroutable address in passive reply" issue is something ftptest.net chokes on, while FileZilla proceeds by reusing the known server address.

`Reply: 227 Entering Passive Mode (10,0,0,4,195,127).`

Is the local IP being returned here a bug, or some misconfiguration with my server?

**Comment by fubar-coder** [comment]
The FTP server doesn't know its public IP address when you're using NAT. I'll open a new issue for this feature.

**Comment by avonheimburg** [comment]
No need. I added a FTP server parameter "PasvAddress" my pull request #50, which you already merged. It is the exact setting you are looking for.

**Comment by fubar-coder** [comment]
@ArrowCase : There is no such thing as `ShutdownAsync` in `SslStream` for net461/netstandard2.0. There isn't even an `Close` method for `netstandard1.3`.

**Comment by ArrowCase** [comment]
@fubar-coder That's an annoying omission from netstandard20. Apparently the changes were done in time for its release but weren't considered in-scope.

I can confirm that @avonheimburg's changes fix both the initial TLS connection problem and the passive address behind NAT/firewall issue. Do you want to keep using this issue for the SslStream stuff, or clsoe it and I can make another one focused on that?

**Comment by fubar-coder** [comment]
I can reopen issue #49 and close this one.

**Comment by cris88** [comment]
> No need. I added a FTP server parameter "PasvAddress" my pull request #50, which you already merged. It is the exact setting you are looking for.

Hello, how do I set that pasvAddress. I'm trying to mount an custom implementation of FTPServer using your nuget on a Docker server but I'm facing a lot of problems. One of them is that I want to set this passive address to public endpoint. How can I do this? Thanks
