### ISSUE TITLE
File system type not communicated correctly

### ISSUE THREAD

**Issue by Marvin-Brouwer** [FubarDevelopment/FtpServer#46]
My current file system is Windows but when I try to connect with this the ftp reading library throws up because it thinks Linux files are served.

I'm using this library:
https://github.com/sparkeh9/CoreFTP
Apparently it determines the filesystem based on the "FEAT" request

**Comment by fubar-coder** [comment]
I found your CoreFTP issue (sparkeh9/CoreFTP#41). I couldn't see in the GitHub repository where there is a distinction between Windows and Unix except the IListDirectoryParser implementations, but you should ensure that `MLSD` is used istead of the "old" LIST command. I also couldn't find anything about the `MSIL` feature you mentioned.

Usually the FTP clients are issuing a `SYST` command whose response is configurable using the `SystCommandOptions`.

**Comment by Marvin-Brouwer** [comment]
Hi, 

I'm sorry I made a typo and stayed with it I guess.
I did configure my SYST command to return Windows_NT and that works however the CoreFTP package still uses a linux file parser.
![image](https://user-images.githubusercontent.com/5499778/50086428-4fe0d880-01fd-11e9-82b2-00e53e051452.png)

Again I understand the ftp package determines whether or not to use MLSD based on the response of the FEAT request, this is the response that is returned now:
```Command:	FEAT
Response:	211-Extensions supported:
Response:	 MDTM
Response:	 MFCT
Response:	 MFF modify;create;
Response:	 MFMT
Response:	 MLST type*;size*;perm*;modify*;create*;
Response:	 UTF8
Response:	 EPSV
Response:	 EPRT
Response:	 REST STREAM
Response:	 SIZE
Response:	211 END```
https://github.com/sparkeh9/CoreFTP/blob/836f25900bd56c89c4b285c51406b52f72b1ece0/src/CoreFtp/FtpClientFeaturesExtensions.cs

**Comment by Marvin-Brouwer** [comment]
I made a workaround by creating my own FEAT command handler that hardcodes the MLSD into there.
![image](https://user-images.githubusercontent.com/5499778/50087438-591f7480-0200-11e9-8502-174c47a6e94d.png)
