### ISSUE TITLE
Firefox doesn't show first item in directory

### ISSUE THREAD

**Issue by ArrowCase** [FubarDevelopment/FtpServer#56]
Steps to reproduce: Create an FtpServer instance serving a directory with more than one file/folder. Navigate to the server in Firefox. Observe that the (alphabetically) first entry in your directory, whether it's a file or folder, is not shown by Firefox.

This might be a bug in Firefox, since all other clients I've tested (including Chrome) don't have this problem, but I wanted to document it here anyway.

Firefox's internal FTP logging shows it executing `PASV` followed by `CWD /` followed by `LIST` when displaying the directory listing. Unfortunately it doesn't display the data received or how it's interpreting that data, so I want to investigate this a little more.

If I can't find anything, I think this can probably be closed sooner rather than later.

**Comment by fubar-coder** [comment]
Will be fixed in 3.0.0-rc.4 or 3.0.0 (whatever comes first).
