### ISSUE TITLE
master source code download vs NuGet packages

### ISSUE THREAD

**Issue by projecta98** [FubarDevelopment/FtpServer#59]
I created a small test FTP server (with some custom connection handling) using master source code (by downloading the .zip file).

Now, I am trying to compile it against the NuGet package (I have tried the 2.0.0 and v3.0.0-beta3) but my application does not compile. It looks like number of classes have changed (e.g. PassCommandHandler and FtpConnection having different signatures as compared to the downloaded source code).

Any suggestion on resolving these issues will be appreciated.

**Comment by fubar-coder** [comment]
You have to use the source code with the given tag.
