### ISSUE TITLE
Cannot connect using version 2.2.0

### ISSUE THREAD

**Issue by lfalck** [FubarDevelopment/FtpServer#63]
Hi! 

I can't connect to the FTP server using version 2.2.0, but 2.1.1 works great. Am i doing something wrong? I tried with both WinSCP, FileZilla and the Windows `ftp` command.

I am using Windows 10 Pro, Version 1809 (OS Build 17763.437). I also tried on Windows Server 2016 Version 1607 (OS Build 14393.2724).

[Here](https://github.com/lfalck/FtpServerConsoleTest) is a minimal example. **ConsoleAppFtpServer21** works for me but i cannot connect using **ConsoleAppFtpServer22**. 

I also included the logs from WinSCP [here](https://github.com/lfalck/FtpServerConsoleTest/blob/master/ConsoleAppFtpServer22/WinSCP.log) and from FileZilla [here](https://github.com/lfalck/FtpServerConsoleTest/blob/master/ConsoleAppFtpServer22/FileZilla.log). They do not say much though.

Love this project by the way, great work! 👍

**Comment by fubar-coder** [comment]
It looks like an exception occurred on the server side. I currently don't have access to a computer. Maybe you can attach the server log too?

**Comment by lfalck** [comment]
OK this is weird, when i added logging version 2.2 started working!

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();

var services = new ServiceCollection();

// When i comment out this line, i can't connect again
services.AddLogging(lb => lb.AddSerilog());
```

**Comment by fubar-coder** [comment]
Ok, that's definitely a bug.

**Comment by fubar-coder** [comment]
2.2.1 is published and should be available soon.

**Comment by lfalck** [comment]
Thanks, now it works!
