### ISSUE TITLE
Bind on 0.0.0.0

### ISSUE THREAD

**Issue by clintnetwork** [FubarDevelopment/FtpServer#65]
Hi,

When I listen on 0.0.0.0 it throw an error, do you know the reason ? 

```IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address```

You need to change `public string ServerAddress { get; set; }` to a IPAddress to add the possibility to use IPAddress.Any or simply add a wildcard like `*`

Thanks

**Comment by fubar-coder** [comment]
I'm unable to reproduce this problem. I remember having problems  with some older versions of the FTP server, but those should be fixed in 2.2.1.

I tested it with both Linux and Windows, with the following commands:

- `sudo dotnet run -- -a "0.0.0.0" in-memory`
- `sudo dotnet run -- -a "::" in-memory`
- `sudo dotnet run -- -a "*" in-memory`

**Comment by clintnetwork** [comment]
Do you have tried the library directly ?

**Comment by fubar-coder** [comment]
Will do

**Comment by fubar-coder** [comment]
I created a program (same as the quickstart sample) and used the library in version 2.2.1. Everything works as expected - both under Linux and Windows.

Do you use .NET Core, .NET Framework, or Mono on Windows or Linux?

**Comment by clintnetwork** [comment]
.Net core / windows and linux, please send me the snippet that you use to bind on 0.0.0.0

**Comment by fubar-coder** [comment]
Here's a test project that binds the server to 0.0.0.0 (without logging).

[TestFtpServer.zip](https://github.com/FubarDevelopment/FtpServer/files/3168389/TestFtpServer.zip)

**Comment by clintnetwork** [comment]
Yes I confirm that it works, on linux normally I'm already in root, I will try and keep you informed

**Comment by clintnetwork** [comment]
We use it for https://clicksguard.io and it works fine !

![image](https://user-images.githubusercontent.com/5221349/58111665-31d73400-7bf2-11e9-81d1-33db8904e05d.png)
