### ISSUE TITLE
ActiveConnections Counter is not thread Safe

### ISSUE THREAD

**Issue by sparkie79** [FubarDevelopment/FtpServer#68]
ActiveConnections Counter for limiting the number o active connectionsto MaxActiveConnections is not thread safe 

[https://csharp.2000things.com/2014/05/20/1100-increment-and-decrement-operators-are-not-thread-safe/](url)

Multiple connection closed in the same instant can lead to incorrect active connection count

**Comment by fubar-coder** [comment]
Fixed in 3.0.0-rc.2
