### ISSUE TITLE
Does FubarDev allow non-anonymous authentication?

### ISSUE THREAD

**Issue by CalebOwusuMI** [FubarDevelopment/FtpServer#69]
Hi!

Thanks for providing this library; it's really useful. 

We'd like to mock an SFTP server using non-anonymous authentication. Is that possible with (the latest release of) FubarDev/FtpServer?

Best regards,

Caleb

**Comment by fubar-coder** [comment]
I'm not entirely sure what you mean.

1. You can use the PAM authentication, but this requires .NET Core 3.0 (currently in preview 5)
2. You can always implement (and register) your own `IMembershipProvider` implementation

BTW: This library only supports `FTPS` (FTP over SSL), not `SFTP` (SSH with FTP-like access).

**Comment by CalebOwusuMI** [comment]
Thanks for the quick reply!

Ah, I should have clarified. This [page](https://github.com/FubarDevelopment/FtpServer/blob/master/docfx_project/articles/authentication.md) states that only anonymous authentication is supported, but we'd like to mock an SFTP server.

You've answered my question, though; I wasn't aware that this library doesn't support SFTP.

Thanks again.
