### ISSUE TITLE
STOR/RETR Will not start data transfer in explicit/implicit ftps

### ISSUE THREAD

**Issue by jwhite1012** [FubarDevelopment/FtpServer#7]
When utilizing AuthTls command handler, everything works fine for insecure calls but explicit/implicit it seems that it hangs up when trying to store or retrieve a file and throws an exception on AuthenticateAsServerAsync in ProtCommandHandler.  I have attached both the logs from NLog with FTP Server and FileZilla to connect locally.

[Log_FileZilla.txt](https://github.com/FubarDevelopment/FtpServer/files/127980/Log_FileZilla.txt)
[NLog_FtpServer.txt](https://github.com/FubarDevelopment/FtpServer/files/127981/NLog_FtpServer.txt)

**Comment by jwhite1012** [comment]
Nevermind - figured out the issue.

**Comment by fubar-coder** [comment]
I'm curious, what was the problem?
