### ISSUE TITLE
Remote ip address in custom FileSystem

### ISSUE THREAD

**Issue by NonInspirationalName** [FubarDevelopment/FtpServer#71]
Hi,

I ran into an obstacle, and I am not quite sure if I am approaching it from the right angle.

I have created a custom MembershipProvider, where ValidateUserAsync does the authentication and then returns a custom IFTPUser back so that I have some extra information available later on.

However, now I need to get the RemoteIP address. The current call into IMembershipProvider.ValidateUserAsync can not provide that to me, as it only has username/password.

In the end, I need the remoteIP address in a custom IUnixFileEntry. It calls a remote service, which needs the original remote IP for logging purposes etc.

The remote IP address is obviously available somewhere, but how can I get that at the creation of my filesystem?

**Comment by fubar-coder** [comment]
Yes, you can access it.

# Version 2.x

* Request the `IFtpConnectionAccessor` service via dependency injection
* Get the current connection (not available in the file system factory, but is available when the file system gets created)
* Remote address should be available through the `IFtpConnection.Data` property

# Version 3.x

* Request the `IFtpConnectionAccessor` service via dependency injection
* Get the current connection (not available in the file system factory, but is available when the file system gets created)
* Get the `IConnectionFeature` feature from the feature collection of the connection (`IFtpConnection.Features`)
