### ISSUE TITLE
Error with validateScopes = true using version 3.0rc4

### ISSUE THREAD

**Issue by lfalck** [FubarDevelopment/FtpServer#72]
Hi!

When i build the service provider with validation of scopes like this:
`services.BuildServiceProvider(validateScopes: true)`

I get this error:
`Cannot resolve scoped service 'FubarDev.FtpServer.Commands.IFtpCommandHandlerProvider' from root provider.`

ValidateScopes is also true when using [CreateDefaultBuilder ](https://source.dot.net/#Microsoft.AspNetCore/WebHost.cs,200)in ASP.NET Core which is where i encountered the issue.

[Here ](https://github.com/lfalck/FtpServerConsoleTest/blob/master/ConsoleAppFtpServer30rc4/Program.cs)is a minimal example of the issue, if i remove validateScopes i can connect but with it the application crashes.

Great work with 3.0, looking foward to the release!

/Ludvig

**Comment by fubar-coder** [comment]
Fixed in RC5 (should be available soon)

**Comment by lfalck** [comment]
Great, thanks!
