### ISSUE TITLE
HELP: Helping with passivePorts and address

### ISSUE THREAD

**Issue by cris88** [FubarDevelopment/FtpServer#98]
Hello. I'm trying to mount an custom implementation of FTPServer using your nuget on a Docker server but I'm facing a lot of problems. One of them is that I want to set this passive address to public endpoint and ports. How can I do this? 

I'm trying to:
services.Configure(opt => new SimplePasvOptions()
{
PasvMinPort = 12000,
PasvMaxPort = 12020,
PublicAddress = System.Net.IPAddress.Parse("###publicaddress###")
});

This doesn't work...

Thanks.

**Comment by unknownguy** [comment]
Did you manage to make this work in docker?

**Comment by fubar-coder** [comment]
The public address is only given to the client when via EPSV, not PASV, because PASV only returns the port - not the IP address.
